### ISSUE TITLE
Add the ability to redirect to a new window

### ISSUE THREAD

**Issue by ghost** [Juicy/juicy-redirect#1]
Add the ability to redirect to a new window with some new attribute like the `target` attribute on `<a>`

Example:
`<link is="juicy-redirect" target="_blank" url="http://www.google.com"></juicy-redirect>`

**Comment by ghost** [comment]
When i use target="_blank"  my chrome browser sais in the adress bar: "Pup-ups was blocked on this page"  and ignore to open the page..  any idé how to go around?

![image](https://cloud.githubusercontent.com/assets/2656996/11718422/2469ad24-9f56-11e5-8694-078d125b69d0.png)

**Comment by tomalec** [comment]
It seems that:

>  A browser will only open a tab/popup without the popup blocker warning, if the command to open the tab/popup comes from a trusted event. That means: The user has to actively click somewhere to open a popup

http://stackoverflow.com/a/19279442

So the extreme clean solution would be to mark a button/input/whatever was clicked that triggered the action to puppet. Then to make puppet handle such flag, and send request synchronously then redirect. What is even harder we will have to make binding work also synchronously.

@warpech, @miyconst  do you have any better ideas?

@andwah Could you elaborate more on your use case?

**Comment by miyconst** [comment]
I think this problem should be solved on UI design level.

@warpech linked me this article as when to use `_blank`: https://css-tricks.com/use-target_blank/

If Chrome (and other browsers) block opening of new window without user action, and we manage to somehow "cheat" on it, then we can't be sure that someday Chrome developers will figure out this and block it again.

Need more input from @andwah, when it is required to open a new tab without user action.

**Comment by ghost** [comment]
> Could you elaborate more on your use case?

When a user clicks on a button in the playground app, the app creates the playground asynchronously. Eventually when the work id done (can take seconds) i want to open up a new window with the newly created playground.

**Comment by miyconst** [comment]
Not a good idea, I think.

Better show a message (maybe modal):

> Your playground has been successfully created and available here: http://alby-424.mysampleapp.com/

**Comment by tomalec** [comment]
Personally, I favor the behavior @miyconst described.
Or even instead of a modal, put such message near by the button I have clicked.
I think it's quite common in use cases, when user requested a result that may come after w while.

As, new tab/popup will steal my focus (HTML, and real, human one).

**Comment by ghost** [comment]
Lets say the delay is sometimes 1sec, then the user will be anoyed why he need to click again.. 

Senario: the user clicks a link and a modal shows "click ok to go to link" :-)

We know what the user want, why not help the user?

**Comment by ghost** [comment]
> As, new tab/popup will steal my focus (HTML, and real, human one).

Yes that's is not good. the user should be "in control".

**Comment by ghost** [comment]
Maybe when user clicks "Create my playground" a modal is displayed "Creating playground...." and when the playground is created the modal is closed and we navigate to the playground in a new or same window?

**Comment by tomalec** [comment]
I would change it to :
1. User click "create new playgroud"
2. Next to the button, or at the tool tip over the button, appears "creating your playground"
3. When creation finishes new button appears "open playground XYZ"

Without any modal, pop-up, pop-up blocker problems, the messages would reflect what's happening, so the user will be happy to se the progress of his action

Then even if the playground creation takes 100ms, it should not be too confusing, if you create a folder, it's quite ok, that you need to click once again to open it.

But, this is just my personal opinion.

We can try to implement synchronous Puppet flow, but this would also require changes in the Playouground app.

**Comment by ghost** [comment]
The button will be on the application page in the appstore client and called "Try now" ..

btw, what do you think if we navigate to the playgound in the same window?

**Comment by tomalec** [comment]
Ok
1. Click on "Try now"
2. Show "creating new playground..."
3. Change button to "Go to playgroud"

Does not look "now" enough ;)
In my opinion, in such case opening playground in the same window is way
much better than in popup. Then we could make also ctrl+click open the new
tab/window, with "creating playground.." which redirect in this its window
to new playground.
11 gru 2015 20:17 "Anders Wahlgren" notifications@github.com napisał(a):

**Comment by ghost** [comment]
Im not so found of buttons that changes behaviour "Try now" => "Go to playground".  but anyway i will try and see how it feels to open the playground in the same window. maybe it feels natural.

@tomalec thanks for the feedback.
