### ISSUE TITLE
Remove the "history" attribute

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-redirect#2]
There is a problem with the `history` attribute in `juicy-redirect` - it has no effect in PuppetJS.

For that, you need to use `link is="puppet-redirect" history`.

It is too simple to make a mistake of using `link is="juicy-redirect" history`, so we have 2 options:
1. remove the `history` attribute from `juicy-redirect`
2. merge `puppet-redirect` features into PuppetDOM and then discontinue `puppet-redirect`

**Comment by ubbeK** [comment]
@warpech: Is this issue still relevant? The `history` attribute is a very useful functionality.

**Comment by warpech** [comment]
The issue is still relevant. The problem that I have is that `juicy-redirect` and `palindrom-redirect` are almost the same. They only differ in the element name and the event names.

We could remove `history` attribute and the usage of History API from `juicy-redirect`, and then change `palindrom-redirect` to only have the history and Palindrom aware mode of operation.

**Comment by warpech** [comment]
Closing as won't fix because this repo is deprecated. See https://github.com/Juicy/juicy-redirect/issues/7 for details.
