### ISSUE TITLE
Deprecate this repo

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-redirect#7]
It seems, with Palindrom/palindrom-redirect used for most of our cases, there is no much need for this element. Then given our short resources, it could be a good idea to drop support for it.

Please vote with reactions 
 - 👍  drop support,
- :-1:  keep it, then comment on your needs,
- 😕 if you would like to have some transition period/release with a warning or smth else.

//cc @Starcounter/webplatformteam

**Comment by warpech** [comment]
As everyone voted in favor, I am deprecating this repo. From now on, the release cycle of `palindrom-redirect` becomes independent of `juicy-redirect`.

I have added a note about the deprecation in `README.md` and in the repo description.
